Ext.define('CoolerIoTMobile.Localization', {
	singleton: true,
	DateTimeFormat: 'd/m/Y h:i A',
	DateTimeWithSecondFormat: 'd/m/Y h:i:s A',
	StandardDate: 'm/d/Y',
	DateFormat: 'h:i A d-M-Y',
	TimeFormat: 'H:i',
	PurityDateFormat: 'Ymd',
	TimeFormatStandard: 'h:i A',
	LoginTitle: 'Please Login',
	UserName: 'User Name',
	UsernamePlaceHolder: 'Username',
	ForgotPassword: 'Forgot Password',
	PasswordTitle: 'Enter Password',
	Password: 'Password',
	Login: 'Login',
	Navigation: 'Navigation',
	LoginLoadingMessage: 'Logging in...',
	LoginValidationMessageTitle: 'Login failed',
	LoginValidationMessage: 'You must specify both username and password',
	AuthenticationFailedTitle: 'Authentication failed',
	AuthenticationFailedMessage: 'Invalid username or password',
	CopyRight: 'Smart cooler powered by <a href="http://www.insigmainc.com/" target="_blank">Insigma</a>, &copy; Copyright 2014, <a href="http://www.insigmainc.com/" target="_blank">Insigma</a> Inc. All rights reserved.',
	Logout: 'Logout',
	CoolSummaryListEmptyText: 'No coolers to display.',
	Scan: 'Scan',
	Debug: 'Debug',
	ProvisionNewDeviceTitle: 'Provision New Device',
	SwitchLanguage: 'Switch Language',
	SwitchTestServer: 'Switch to Test Server',
	SummaryDetails: 'Summary Details',
	FailedMessageTitle: 'Failed',
	SuccessMessageTitle: 'Success',
	MessageTryLater: 'Please retry later.',
	ProductDistribution: 'Product distribution',
	CoolerDetailsListEmptyText: 'No cooler data found',
	ViewData: 'View Data',
	ViewPicture: 'View Pictures',
	DownloadData: 'Download Data',
	TakePicture: 'Take Picture',
	DetailMenu: 'Detail Menu',
	LocationList: 'Locations',
	DeviceData: 'Device Data',
	ConfirmationMessageTitle: 'Confirmation',
	LogoutMessage: 'Are you sure you want to log out?',
	DetailDeviceData: 'Detailed Device Data',
	SearchTags: 'Scanning device',
	CoolSummaryImageEmptyText: 'No image to display',
	CoolerImages: 'Cooler Images',
	ImageFilter: 'Image Filters',
	Processed: 'Processed',
	Purity: 'Purity',
	Stock: 'Stock',
	From: 'From',
	To: 'To',
	Yes: 'Yes',
	No: 'No',
	ForeignProduct: 'Foreign Product',
	Search: 'Search',
	Cancel: 'Cancel',
	Settings: 'Settings',
	Apply: 'Apply',
	Server: 'Server',
	EnableNotification: 'Enable Notification',
	Language: 'Language',
	InRange: 'In Range',
	TooCold: 'Too Cold',
	TooHot: 'Too Hot',
	Bright: 'Bright',
	Low: 'Low',
	Dark: 'Dark',
	Impure: 'Impure',
	Pure: 'Pure',
	LanguageEnglish: 43,
	LanguageHindi: 44,
	LanguageChinese: 45,
	ServerTypeProduction: 41,
	ServerTypeTest: 42,
	NotificationEnable: 46,
	NotificationDisable: 47,
	Date: 'Date',
	LogoutLoadingMessage: 'Logging out',
	DfuSettingTitle: 'Setting Title',
	ChartLoadingMessage: 'Chart Loading',
	FileNotAccessible: 'File selected but not accessible',
	FilesNotFound: 'Files Not found',
	CannotReadFile: 'Can not read file',
	FileNotReadable: 'File is not readable',
	CoolSummaryDetailEmptyText: 'Empty list',
	ErrorLoadingSettings: 'Error loading settings',
	ForgotPassword: 'Forgot Password',
	ForgotPasswordTitleInfo: 'Please enter username/ email<br />&nbsp;',
	Email: 'Email',
	ButtonOk: 'Ok',
	HumidityChart: 'Humidity Chart',
	LightChart: 'Light Chart',
	TemperatureChart: 'Temperature Chart',
	ImageUploadSuccessMessage: 'Image uploaded for asset Id {0}',
	ForiegnProduct: 'Foreign Product',
	Sos: 'SoS',
	CoolerAssetType: 1,
	WendingItemAssetType: 4,
	MatrixListTitle: 'Matrix Data',
	Save: 'Save',
	Browse: 'Browse',
	Upload: 'Upload',
	Uploading: 'Uploading',
	Error: 'Error',
	UnknownError: 'Unknown Error',
	RequestSigningHeaderIsNotDefined: 'Request Signing Not Defined',
	RequestSigningIsFailed: 'Request Signing Failed ',
	MatrixDataEmptyText: 'No matrix data found',
	SmartCoolerTitle: 'Smart Cooler',
	BleTagTitle: 'BLE Tag',
	DebugListTitle: 'List',
	FetchDataTitle: 'Fetch Data',
	DisconnectTitle: 'Disconnect',
	DeviceDataListEmptytext: 'No event data found',
	BluetoothDisabled: 'Bluetooth Disabled',
	BluetoothEnableMessage: 'Please enable bluetooth and try again',
	StopText: 'Stop',
	StartText: 'Start',
	ConnectErrorTitle: 'Connect Error',
	ConnectErrorMessage: 'Please enter valid password',
	ConnectDeviceMessage: 'Please connect device',
	RecordType: 'Record Type',
	Door: 'Door',
	Temperature: 'Temperature',
	Humidity: 'Humidity',
	AmbientLight: 'Ambient Light',
	SoundLevel: 'Sound Level',
	BatteryLevel: 'Battery Level',
	Time: 'Time',
	Healthy: 'Healthy',
	LinearMotion: 'Linear Motion',
	AngularMotion: 'Angular Motion',
	MagnetMotion: 'Magnet Motion',
	DoorEvent: 'Door Event',
	ImageEvent: 'Image Event',
	GpsEvent: 'GPS Event',
	MotionTime: 'Motion Time',
	UnknownRecordType: 'Unknown record type',
	Distance: 'Distance',
	Angle: 'Angle',
	MagnetX: 'Magnet_X',
	MagnetY: 'Magnet_Y',
	MagnetZ: 'Magnet_Z',
	PosXNegX: 'Pos_x/ Neg_x',
	PosYNegY: 'Pos_y/ Neg_y',
	PosZNegZ: 'Pos_z/ Neg_z',
	ImageSize: 'Image Size',
	Commands: 'Commands',
	Status: 'Status',
	StartTimeMovement: 'Start Time Movement',
	EndTimeMovement: 'End Time Movement',
	ConnectDeviceErrorMessage: 'Please connect device first',
	FetchData: 'Request all saved sensor event/data',
	FirmwareDetail: 'Get Firmware Detail',
	CurrentTime: 'Get Current Time',
	GetSerialNumber: 'Get Serial Number of Device',
	RestartDevice: 'Restart Device',
	ResetDevice: 'Reset device',
	SensorOn: 'Turn sensor on',
	SensorOff: 'Turn sensor off',
	CurrentSensorData: 'Read current sensor data',
	EventCount: 'Get event count',
	LatestNEvents: 'Get latest n events',
	EventDataFromIdxIdy: 'Event/data from ID x to ID Y',
	EraseEventData: 'Erase all event data',
	SoundBuzzer: 'Sound Buzzer',
	SetInterval: 'Set interval to read sensor periodically',
	SetRealTimeClock: 'Set real time clock',
	SetGpsLocation: 'Set GPS location of device',
	SetMajorMinorVersion: 'Set Major/ Minor version of device',
	SetSerialNumber: 'Set Serial# of device',
	SetAdvertisingPeriod: 'Set Advertising period',
	SetSensorThreshold: 'Set sensor threshold',
	SetStandbyModeOn: 'Set standby mode on',
	SetStandbyModeOff: 'Set standby mode off',
	SetDeviceInDfu: 'Put device in DFU',
	SetChangePassword: 'Change Password',
	SetRssiForIbeaconFrame: 'Set RSSI for iBeacon Frame',
	ReadConfigurationParameter: 'Read Configuration Parameter',
	ScaningDevice: 'Scanning',
	ResponseData: 'Response Data',
	InputValue: 'Input value',
	SetPasswordTitle: 'Set password(Max 19 bytes)',
	Cancel: 'Cancel',
	Ok: 'Ok',
	SensorGroupTitle: '(0x01 = sensor group, 0x02 = acc group)',
	SensorGroupId: 'Sensor Group Id (0x0)',
	LatestEventTitle: 'Get latest n event',
	LatestEvent: 'Latest Event',
	TotalEvent: 'Total Event',
	MajorVersion: 'Major Version',
	MinorVersion: 'Minor Version',
	TimeOfDevice: 'Time of device',
	DeviceSerialNumber: 'Device Serial Number',
	CurrentEventIndex: 'Current Event Index',
	RangeOfEventId: 'Range of Event Id',
	EventDataTitle: 'Get Event / data records from Event ID X to Event ID Y',
	EventIdX: 'Event Id X',
	EventIdY: 'Event Id Y',
	NumberOfEventSent: 'Number of event that will be sent',
	PeriodicInterval: 'Periodic Interval',
	PeriodicIntervalTitle: 'Set interval to read sensor periodically',
	IntervalValidationError: 'Minutes between 1 to 60',
	SetClockTitle: 'Since 1st Oct 2014(MM/dd/yyyy HH:mm:ss)',
	InvalidDateMessage: 'Invalid Date',
	GpsLocationTitle: 'Set GPS location of device',
	Latitude: 'Latitude',
	Longitude: 'Longitude',
	Major: 'Major',
	Minor: 'Minor',
	MajorMinorTitle: 'Set Major/ Minor version of device',
	SerialNumberTitle: 'Set Serial# of device',
	SerialNumber: 'Serial',
	Milliseconds: 'Milliseconds',
	TemperatureOutOfThreashold: 'Temperature out of threshold',
	LightOutOfThreashold: 'Light out of threshold',
	HumidityOutOfThreashold: 'Humidity out of threshold',
	SoundOutOfThreashold: 'Sound out of threshold',
	SetRssiTitle: 'RSSI value for 1 meter distance(0 - 255)',
	RssiTitleInMeter: 'RSSI value for 1 meter distance',
	RssiValue: 'RSSI value',
	PacketId: 'Packet Id',
	PeriodicIntervalMinutes: 'Periodic Interval (In Minutes)',
	AdvertisingPeriodMilliseconds: 'Advertising Period (MilliSeconds)',
	StandbyControl: 'Standby Control',
	SensorGroup1PowerStatus: 'Sensor Group-1 Power status',
	SensorGroup2PowerStatus: 'Sensor Group-2 Power status',
	AssetListTitle: 'Cooler',
	CustomerTitle: 'Customer',
	AlertTitle: 'Alert',
	SmartDeviceTitle: 'Smart Device',
	AssetTitle: 'Asset',
	VisitTitle: 'Visit',
	ToDoListTitle: 'To-Do List',
	MessageTitle: 'Messages',
	ObjectiveTitle: 'Objectives',
	LogoffTitle: 'Logout',
	AddToRoute: 'Add to Route',
	InStore: 'In Store',
	PhoneOrder: 'Phone Order',
	MovementThresholdG: 'Movement Threshold G Value',
	MovementThresholdTime: 'Movement Threshold Time',
	ModifyLastReadIndex: 'Modify Last Read Index',
	SETBLEMajorMinor: 'SET BLE Major/Minor',
	FactorySetup: 'Factory Setup',
	ReadUnreadEvents: 'Read Unread Events',
	ReadAllData: 'Read all data',
	ReadCurrentData: 'Read Current Data',
	GetConfiguration: 'Get Configuration',
	DFU: 'DFU',
	InstallDevice: 'Install Device',
	GetOldestNEvents: 'Get Oldest n Events',
	SetIbeaconUUID: 'Set Ibeacon UUID',
	SetMacAddress: 'Set Mac Address',
	PutDeviceInDeepSleep: 'Put Device In Deep Sleep',
	UUID: 'UUID',
	MacAddress: 'Mac Address',
	Movement: 'movement',
	Duration: 'Duration',
	DownloadImage: 'Download Image',
	ImageCalibration: 'Image Calibration',
	ViewImage: 'View Image',
	SetDoorOpenAngle: 'Set Door Open Angle',
	SetCameraSetting: 'Set Camera Setting',
	EnableTakePicture: 'Enable Take Picture',
	DisableTakePicture: 'Disable Take Picture',
	ResetCameraSetting: 'Reset Camera Setting',
	CalibrateGyro: 'Calibrate Gyro',
	FactorySetupSmartTag: 'Factory Setup SmartTag',
	FactorySetupSmartVision: 'Factory Setup SmartVision',
	ResetMacAddress: 'Reset MacAddress',
	SmartHubDFU: 'Smart Hub DFU',
	ThresholdAngle: 'Threshold Angle in Degree',
	TriggerDelta: 'Trigger Delta in degrees',
	Brightness: 'Brightness',
	Contrast: 'Contrast',
	Saturation: 'Saturation',
	ShutterSpeed: 'Shutter Speed',
	CameraQuality: 'Camera Quality',
	Effect: 'Effect',
	LightMode: 'Light Mode',
	CameraClock: 'Camera Clock',
	Cdly: 'Cdly',
	Drive: 'Drive',
	Sequence: 'Sequence',
	Address: 'Address',
	SetCommands: 'Set Commands',
	DateWithSecondFormat: 'm/d/Y h:i:s A',
	Logs: 'Logs',
	PilotUrl: 'https://test.cooleriot.com',
	ProductionAzureUrl: 'https://poccooler.azurewebsites.net',
	ProductionV2Url: 'https://prod.cooleriot.com',
	QAUrl: 'https://qa.cooleriot.com',
	DebugUrl: 'http://192.168.2.88/Cooler',
	StagingUrl: 'https://staging.cooleriot.com',
	InstallDeviceNote: 'Note: Door must be closed while performing install device',
	Admin: 'Admin',
	MonthDateTimeFormat: 'm/d/Y h:i.u A',
	Exit: 'Exit',
	InstallDevice: 'Install Device'
});