Ext.define("CoolerIoTMobile.view.Mobile.CommandsNavigation", {
	extend: 'Ext.List',
	xtype: 'commandsNavigation',
	config: {
		itemTpl: "<span class='menu-list-items'><div>{SlideMenu}</div></span>",
		cls: 'background-white-container',
		data: [
			{ SlideMenu: CoolerIoTMobile.Localization.SetCommands, MenuId: -111, parentId: 0, isSmartVision: false },
			//{ SlideMenu: CoolerIoTMobile.Localization.ModifyLastReadIndex, MenuId: CoolerIoTMobile.BleCommands.MODIFY_LAST_READ_EVENT_INDEX, parentId: -111, isSmartVision: false },
			{ SlideMenu: CoolerIoTMobile.Localization.SetSensorThreshold, MenuId: CoolerIoTMobile.BleCommands.SET_SENSOR_THRESHOLD, parentId: -111, isSmartVision: false },
			{ SlideMenu: CoolerIoTMobile.Localization.SetStandbyModeOn, MenuId: CoolerIoTMobile.BleCommands.SET_STANDBY_MODE, flag: 1, parentId: -111, isSmartVision: false },
            { SlideMenu: CoolerIoTMobile.Localization.SetStandbyModeOff, MenuId: CoolerIoTMobile.BleCommands.SET_STANDBY_MODE, flag: 0, parentId: -111, isSmartVision: false },
			//{ SlideMenu: CoolerIoTMobile.Localization.SetDoorOpenAngle, MenuId: CoolerIoTMobile.BleCommands.SET_DOOR_OPEN_ANGLE, parentId: -111, isSmartVision: false },
			{ SlideMenu: CoolerIoTMobile.Localization.SetCameraSetting, MenuId: CoolerIoTMobile.BleCommands.SET_CAMERA_SETTING, parentId: -111, isSmartVision: true },
			{ SlideMenu: CoolerIoTMobile.Localization.EnableTakePicture, MenuId: CoolerIoTMobile.BleCommands.ENABLE_TAKE_PICTURE, flag: 01, parentId: -111, isSmartVision: true },
            { SlideMenu: CoolerIoTMobile.Localization.DisableTakePicture, MenuId: CoolerIoTMobile.BleCommands.ENABLE_TAKE_PICTURE, flag: 00, parentId: -111, isSmartVision: true },
			{ SlideMenu: CoolerIoTMobile.Localization.SETBLEMajorMinor, MenuId: CoolerIoTMobile.BleCommands.SET_MAJOR_MINOR_VERSION, parentId: -111, isSmartVision: false },
			{ SlideMenu: CoolerIoTMobile.Localization.ResetCameraSetting, MenuId: CoolerIoTMobile.BleCommands.SET_CAMERA_FACTORY_DEFAULT_SETTING, parentId: -111, isSmartVision: true },
			{ SlideMenu: CoolerIoTMobile.Localization.CalibrateGyro, MenuId: CoolerIoTMobile.BleCommands.READ_CALIBRATE_GYRO, parentId: -111, isSmartVision: true },
			{ SlideMenu: CoolerIoTMobile.Localization.FactorySetup, MenuId: -222, parentId: 0, isSmartVision: false },
			{ SlideMenu: CoolerIoTMobile.Localization.ResetDevice, MenuId: CoolerIoTMobile.BleCommands.RESET_DEVICE, parentId: -222, isSmartVision: false },
			{ SlideMenu: CoolerIoTMobile.Localization.FactorySetup, MenuId: CoolerIoTMobile.BleCommands.FACTORY_SETUP, parentId: -222, isSmartVision: false },
			{ SlideMenu: CoolerIoTMobile.Localization.SetIbeaconUUID, MenuId: CoolerIoTMobile.BleCommands.SET_IBEACON_UUID, parentId: -222, isSmartVision: false },
			{ SlideMenu: CoolerIoTMobile.Localization.GetSerialNumber, MenuId: CoolerIoTMobile.BleCommands.SERIALNUMBER, parentId: -222, isSmartVision: false },
			{ SlideMenu: CoolerIoTMobile.Localization.SetMacAddress, MenuId: CoolerIoTMobile.BleCommands.SET_MAC_ADDRESS, parentId: -222, isSmartVision: false },
			{ SlideMenu: CoolerIoTMobile.Localization.ResetMacAddress, MenuId: CoolerIoTMobile.BleCommands.RESET_MAC_ADDRESS, parentId: -222, isSmartVision: false },
			{ SlideMenu: CoolerIoTMobile.Localization.PutDeviceInDeepSleep, MenuId: CoolerIoTMobile.BleCommands.SET_DEEP_SLEEP, parentId: -222, isSmartVision: false },
			{ SlideMenu: CoolerIoTMobile.Localization.SmartHubDFU, MenuId: 0, parentId: -222, isSmartVision: false },
			{ SlideMenu: CoolerIoTMobile.Localization.ReadUnreadEvents, MenuId: CoolerIoTMobile.BleCommands.READ_AVAILABLE_UNREAD_EVENT, parentId: 0, isSmartVision: false },
			{ SlideMenu: CoolerIoTMobile.Localization.ReadAllData, MenuId: CoolerIoTMobile.BleCommands.FETCH_DATA, parentId: 0, isSmartVision: false },
			{ SlideMenu: CoolerIoTMobile.Localization.ReadCurrentData, MenuId: CoolerIoTMobile.BleCommands.CURRENT_SENSOR_DATA, parentId: 0, isSmartVision: false },
			{ SlideMenu: CoolerIoTMobile.Localization.EraseEventData, MenuId: CoolerIoTMobile.BleCommands.ERASE_EVENT_DATA, parentId: 0, isSmartVision: false },
			{ SlideMenu: CoolerIoTMobile.Localization.TakePicture, MenuId: CoolerIoTMobile.BleCommands.TAKE_PICTURE, parentId: 0, isSmartVision: true },
			{ SlideMenu: CoolerIoTMobile.Localization.DownloadImage, MenuId: CoolerIoTMobile.BleCommands.READ_IMAGE_DATA, parentId: 0, isSmartVision: true },
			{ SlideMenu: CoolerIoTMobile.Localization.ViewImage, MenuId: CoolerIoTMobile.BleCommands.View_Image, parentId: 0, isSmartVision: true },
			{ SlideMenu: CoolerIoTMobile.Localization.CurrentTime, MenuId: CoolerIoTMobile.BleCommands.CURRENT_TIME, parentId: 0, isSmartVision: false },
			{ SlideMenu: CoolerIoTMobile.Localization.EventCount, MenuId: CoolerIoTMobile.BleCommands.EVENT_COUNT, parentId: 0, isSmartVision: false },
			{ SlideMenu: CoolerIoTMobile.Localization.GetConfiguration, MenuId: CoolerIoTMobile.BleCommands.READ_CONFIGURATION_PARAMETER, parentId: 0, isSmartVision: false },
			{ SlideMenu: CoolerIoTMobile.Localization.RestartDevice, MenuId: CoolerIoTMobile.BleCommands.RESTART_DEVICE, parentId: 0, isSmartVision: false },
			{ SlideMenu: CoolerIoTMobile.Localization.ImageCalibration, MenuId: CoolerIoTMobile.BleCommands.READ_CAMERA_SETTING, parentId: 0, isSmartVision: true },
			{ SlideMenu: CoolerIoTMobile.Localization.SetChangePassword, MenuId: CoolerIoTMobile.BleCommands.SET_CHANGE_PASSWORD, parentId: 0, isSmartVision: false },
			{ SlideMenu: CoolerIoTMobile.Localization.GetOldestNEvents, MenuId: CoolerIoTMobile.BleCommands.READ_OLDEST_N_EVENT, parentId: 0, isSmartVision: false }
		]
	}
});
