Ext.define('CoolerIoTMobile.view.Mobile.Location', {
	extend: 'Ext.List',
	xtype: 'mobile-location',
	config: {
		flex: 1,
		itemHeight: 30,
		loadingText: false,
		itemTpl: new Ext.XTemplate('<div asset-item-container>',
			'<ul class= "background-white-container">',
			'<span class="cooleriot-table-cell text-center iot-col-12_5">',
				'<span class="customer-mid-span">',
					'<div class="location-name">{Name} ({Code})</div>',
				'</span>',
				'</span>',
			'<span class="cooleriot-table-cell text-center iot-col-12_5">',
				'<span >',
					'<div class="location-icons">',
						'<tpl if="IsKeyLocation == true">',
							'<div class="keylocation"></div>',
						'</tpl>',
						'<tpl if="OpenHealthAlert &gt; 0">',
							'<div class="nothealthy"></div>',
						 '</tpl>',
						'<tpl if="WasOffRoute == true">',
							'<div class="unschedule"></div>',
						'</tpl>',
						'<tpl if="OpenPurityAlert &gt; 0">',
							'<div class="purityissue"></div>',
						'</tpl>',
						'<tpl if="OpenMissingAlert &gt; 0">',
							'<div class="missingissue"></div>',
						'</tpl>',
						'<tpl if="OpenMovementAlert &gt; 0">',
							'<div class="movementissue"></div>',
						'</tpl>',
						'<tpl if="OpenStockAlert &gt; 0">',
							'<div class="stockissue"></div>',
						'</tpl>',
					'</div>',
				'</span>',
			'</span>',
			'</ul>',
			'</div>'
		)
	}
});
