Ext.define('CoolerIoTMobile.view.Mobile.SmartDeviceHealthRecord', {
	extend: 'Ext.dataview.List',
	xtype: 'smartDeviceHealthRecord',
	config: {
		plugins: [
             {
             	xclass: 'Ext.plugin.ListPaging',
             	pullRefereshText: 'Pull To Refresh',
             	autoPaging: true
             }
		],
		title: 'Health Data',
		emptyText: 'No Data',
		store: 'SmartDeviceHealthRecord',
		striped: true,
		cls: 'asset-item-list-container',
		itemTpl: new Ext.XTemplate(
			'<div class="asset-item-container asset-item-health-container">',
                            '<ul class="cooleriot-list-view">',
							'<li class="asset-first-row cooleriot-display-table">',
								'<span class="cooleriot-table-cell text-center iot-col-12_5">',
									'<span class="iot-mid-span">',
										'<span class=" iot-icon iot-eventstart-icon"></span>',
									'</span>',
								'</span>',
								'<span class="cooleriot-table-cell text-center iot-col-12_5">',
									'<span class="iot-mid-span">',
										'<span class=" iot-icon iot-temp-icon"></span>',
									'</span>',
								'</span>',
								'<span class="cooleriot-table-cell text-center iot-col-12_5">',
									'<span class="iot-mid-span">',
										'<span class=" iot-icon iot-light-icon"></span>',
									'</span>',
								'</span>',
								'<span class="cooleriot-table-cell text-center iot-col-12_5">',
									'<span class="iot-mid-span">',
										'<span class=" iot-icon iot-humidity-icon"></span>',
									'</span>',
								'</span>',
								'<span class="cooleriot-table-cell text-center iot-col-12_5">',
									'<span class="iot-mid-span">',
										'<span class=" iot-icon iot-door-icon"></span>',
									'</span>',
								'</span>',
								'<tpl if="SmartDeviceTypeId == CoolerIoTMobile.Enums.SmartDeviceType.SmartHub">',
								'<span class="cooleriot-table-cell text-center iot-col-12_5">',
									'<span class="iot-mid-span">',
										'<span class=" iot-icon iot-power-icon"></span>',
									'</span>',
								'</span>',
								'</tpl>',
							'</li>',
							'<li class="cooleriot-display-table asset-second-row">',
								'<span class="cooleriot-table-cell text-center iot-col-12_5">{[CoolerIoTMobile.util.Renderers.standardTime(values.EventTime)]}</span>',
								'<span class="cooleriot-table-cell text-center iot-col-12_5">{Temperature}</span>',
								'<span class="cooleriot-table-cell text-center iot-col-12_5">{LightIntensity}</span>',
								'<span class="cooleriot-table-cell text-center iot-col-12_5">{Humidity}</span>',
								'<span class="cooleriot-table-cell text-center iot-col-12_5">{[CoolerIoTMobile.util.Renderers.getStatus(values.IsDoorOpen)]}</span>',
								'<tpl if="SmartDeviceTypeId == CoolerIoTMobile.Enums.SmartDeviceType.SmartHub">',
								'<span class="cooleriot-table-cell text-center iot-col-12_5">{[CoolerIoTMobile.util.Renderers.getPowerText(values)]}</span>',
								'</tpl>',
							'</li>',
						'</ul></div>'
		),
		grouped: true
	}
});